name: Amalgamation_Check

on:
  push:
    branches:
      - develop
      - main
      - release/*
    paths:
      - include/fkYAML/**
      - single_include/fkYAML/**
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{github.workflow}}-${{github.ref || github.run_id}}
  cancel-in-progress: true

jobs:
  amalgamation-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v3

    - name: Check if the amalgamated header file is up-to-date.
      run: make check-amalgamate
