name: Clang_Format_Check

on:
  push:
    paths:
      - '**.hpp'
      - '**.cpp'
  pull_request:
    branches: [ "main", "develop" ]

env:
  BUILD_TYPE: Release

jobs:
  format-check:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - include/fkYAML
          - test/unit_test

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Run clang-format style check
      uses: jidicula/clang-format-action@v4.11.0
      with:
        clang-format-version: '14'
        check-path: ${{matrix.path}}
