name: CMake_Debug

on:
  push:
    paths:
      - '**.hpp'
      - '**.cpp'
      - '**.cmake'
      - '**.cmake.in'
      - '**.pc.in'
      - '**.yml'
  pull_request:
    branches: [ "main", "develop" ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    timeout-minutes: 10
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            run_sanitizers: ON
          - os: windows-latest
            run_sanitizers: OFF
          - os: macos-latest
            run_sanitizers: OFF

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DFK_YAML_CI=ON -DFK_YAML_RUN_SANITIZER=${{matrix.run_sanitizer}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
