name: Coverage

on:
  push:
    branches:
      - develop
      - main
    paths:
      - .github/workflows/coverage.yml
      - cmake/**
      - include/**
      - test/**
      - CMakeLists.txt
      - Makefile
  pull_request:
    paths:
      - .github/workflows/coverage.yml
      - cmake/**
      - include/**
      - test/**
      - CMakeLists.txt
      - Makefile
  workflow_dispatch:

jobs:
  coverage:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install lcov
      run: |
        sudo apt-get update
        sudo apt-get install -y lcov
        lcov -v

    - name: Generate coverage
      run: make lcov-coverage

    - name: Upload coverage to Coveralls
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        file: ${{github.workspace}}/build_coverage/coverage/fkYAML.info
        format: lcov
