name: macOS

on:
  push:
    branches:
      - develop
      - main
      - release/*
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{github.workflow}}-${{github.ref || github.run_id}}
  cancel-in-progress: true

jobs:
  xcode_for_macos11:
    timeout-minutes: 10
    runs-on: macos-11
    strategy:
      matrix:
        xcode: [ '11.7', '12.4', '12.5.1', '13.0', '13.1', '13.2.1' ]
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{matrix.xcode}}.app/Contents/Developer

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Debug -DFK_YAML_BUILD_TEST=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Debug

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C Debug --output-on-failure

  xcode_for_macos12:
    timeout-minutes: 10
    runs-on: macos-12
    strategy:
      matrix:
        xcode: [ '13.1', '13.2.1', '13.3.1', '13.4.1', '14.0.1', '14.1', '14.2' ]
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{matrix.xcode}}.app/Contents/Developer

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Debug -DFK_YAML_BUILD_TEST=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Debug

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C Debug --output-on-failure
