name: PublishDocs

# make the documentation up to date with the develop branch
on:
  push:
    branches:
      - develop
    paths:
      - docs/mkdocs/**
  workflow_dispatch:

# no cancellation during uploads to avoid broken publications
concurrency:
  group: documentation
  cancel-in-progress: false

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    if: github.repository == 'fktn-k/fkYAML'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build documentation
        run: make build -C docs/mkdocs

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload API documents
        uses: actions/upload-pages-artifact@v2
        with:
          path: ${{github.workspace}}/docs/mkdocs/site

  deploy:
    if: github.repository == 'fktn-k/fkYAML'
    needs: build
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
