name: ReleasePackage

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  create_package:
    timeout-minutes: 10
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        single_header: ["ON", "OFF"]
        include:
          - os: ubuntu-latest
            artifact_name: fkYAML.tgz
            single_header: "OFF"
          - os: ubuntu-latest
            artifact_name: fkYAML_single_header.tgz
            single_header: "ON"
          - os: windows-latest
            artifact_name: fkYAML.zip
            single_header: "OFF"
          - os: windows-latest
            artifact_name: fkYAML_single_header.zip
            single_header: "ON"

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="${{github.workspace}}/build/package" -DFK_YAML_USE_SINGLE_HEADER=${{matrix.single_header}}

    - name: Install
      run: |
        cmake --build ${{github.workspace}}/build --config Release --target install
        ls ${{github.workspace}}/build/package

    - name: Package
      shell: bash
      run: |
        ls '${{github.workspace}}/build'
        if [[ "${{ matrix.os }}" == "windows-latest" ]]
        then
          7z a ${{matrix.artifact_name}} '${{github.workspace}}/build/package'
        else
          tar czvf ${{matrix.artifact_name}} '${{github.workspace}}/build/package'
        fi
        ls

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{matrix.artifact_name}}
        path: ${{matrix.artifact_name}}
