name: Ubuntu

on:
  push:
    paths:
      - '**.hpp'
      - '**.cpp'
      - '**.cmake'
      - '**.yml'
  pull_request:
  workflow_dispatch:

jobs:
  ubuntu-latest:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [ Debug, Release ]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build_${{matrix.build_type}} -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DFK_YAML_CI=ON -DFK_YAML_RUN_SANITIZERS=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build_${{matrix.build_type}} --config ${{matrix.build_type}}

    - name: Test
      working-directory: ${{github.workspace}}/build_${{matrix.build_type}}
      run: ctest -C ${{matrix.build_type}} --output-on-failure

  ci-clang_tidy_check:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build_clang_tidy

    - name: Clang-Tidy check
      run: cmake --build ${{github.workspace}}/build_clang_tidy --target run_clang_tidy
