name: Ubuntu

on:
  push:
    paths:
      - '**.hpp'
      - '**.cpp'
      - '**.cmake'
      - '**.yml'
  pull_request:
  workflow_dispatch:

jobs:
  ubuntu-latest:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [ Debug, Release ]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build_${{matrix.build_type}} -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DFK_YAML_DEFAULT_CI=ON -DFK_YAML_RUN_SANITIZERS=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build_${{matrix.build_type}} --config ${{matrix.build_type}}

    - name: Test
      working-directory: ${{github.workspace}}/build_${{matrix.build_type}}
      run: ctest -C ${{matrix.build_type}} --output-on-failure

  ci-clang_tidy_check:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build_clang_tidy

    - name: Clang-Tidy check
      run: cmake --build ${{github.workspace}}/build_clang_tidy --target run_clang_tidy

  tests-for-self-hosted-runner:
    runs-on: self-hosted
    strategy:
      matrix:
        target:
          - ci_test_compiler_clang++-11
          - ci_test_compiler_clang++-12
          - ci_test_compiler_clang++-13
          - ci_test_compiler_clang++-14
          - ci_test_compiler_clang++-15
          - ci_test_compiler_g++-9
          - ci_test_compiler_g++-10
          - ci_test_compiler_g++-11
          - ci_test_compiler_g++-12
          - ci_test_clangxx_cxx11
          - ci_test_clangxx_cxx14
          - ci_test_clangxx_cxx17
          - ci_test_clangxx_cxx20
          - ci_test_clangxx_cxx23
          - ci_test_gxx_cxx11
          - ci_test_gxx_cxx14
          - ci_test_gxx_cxx17
          - ci_test_gxx_cxx20
          - ci_test_gxx_cxx23

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DFK_YAML_CUSTOM_CI=ON

      - name: Run builds & tests for the test target
        run: |
          cmake --build ${{github.workspace}}/build --target ${{matrix.target}}

      - name: Clean up build directories
        run: rm -rf ${{github.workspace}}/build
